// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lguhgosxkwsndfetxbdl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxndWhnb3N4a3dzbmRmZXR4YmRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MDExMDIsImV4cCI6MjA2NzI3NzEwMn0.rZi3N3PtybPDyYG4JohCQOlzWuXipuLWaDvJTHt3HBE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});